### ISSUE TITLE
运行脚本出错，未连接到互联网

### ISSUE THREAD

**Issue by zhaoqingqing** [wangdepin/boss_zhipin#1]
楼主你好，driver我已经配置好了，测试可以正常打开浏览器。
但是在运行start_crawl.py时，出现这个报错

selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
详细堆栈：

`2021-05-26 15:57:54 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.zhipin.com/job_detail/?query=U3Dcity=101010100&industry=&position=>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\twisted\internet\defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "C:\Program Files\Python38\lib\site-packages\scrapy\core\downloader\middleware.py", line 36, in process_request
    response = yield deferred_from_coro(method(request=request, spider=spider))
  File "E:\Code\python_study\bossxr\bossxr\middlewares.py", line 110, in process_request
    self.driver.get(request.url)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=86.0.4240.198)`

然后会打开浏览器，显示未连接到互联网，bossxr.json的内容是空的。
![image](https://user-images.githubusercontent.com/3056814/119623935-3ebf3b80-be3b-11eb-9303-4cea20ae9071.png)

自动代理已经关闭了
![image](https://user-images.githubusercontent.com/3056814/119624027-53033880-be3b-11eb-8ce6-f3cda805631b.png)

**Comment by wangdepin** [comment]
你好，我觉得可能是你们有设置代理，我当时设置了代理能跑通流程

qingqing.zhao ***@***.***> 于2021年5月26日周三 下午4:04写道：

**Comment by zhaoqingqing** [comment]
看我上面的图是关闭了代理，我试了可以网络可以访问zhipie.com。
你是觉得还有其它的网络问题吗？
